package ui

import "../draw2d"
import "../input"
import "core:testing"

@(private)
frame :: proc(t: ^testing.T, ctx: ^Context, state: input.State, second := false) -> Interaction {
	testing.expect(t, begin(ctx, state, {200, 100}, {400, 200}) == .None)
	testing.expect(t, region(ctx, {{10, 10}, {80, 60}}) == .None)
	result, err := interact(ctx, id("first"), {{20, 20}, {60, 20}})
	testing.expect(t, err == .None)
	if second {
		_, second_error := interact(ctx, id("second"), {{20, 45}, {60, 20}})
		testing.expect(t, second_error == .None)
	}

	testing.expect(t, end(ctx) == .None)
	return result
}

@(test)
test_pointer_capture_and_release :: proc(t: ^testing.T) {
	ctx := create()
	defer destroy(&ctx)
	state: input.State
	input.init(&state, true, {60, 60})
	input.record_mouse_button(&state, .Left, true)
	pressed := frame(t, &ctx, state)
	testing.expect(t, pressed.held && pressed.focused && !pressed.clicked)
	game := remaining_input(&ctx)
	testing.expect(t, !input.mouse_down(&game, .Left))
	input.clear(&state)
	input.record_cursor(&state, {300, 160})
	input.record_scroll(&state, {0, 2})
	dragged := frame(t, &ctx, state)
	game = remaining_input(&ctx)
	testing.expect(t, dragged.held && !dragged.hovered && ctx.capture.mouse)
	testing.expect_value(t, game.mouse_delta, ([2]f64{}))
	testing.expect_value(t, game.scroll_delta, ([2]f64{}))
	input.clear(&state)
	input.record_mouse_button(&state, .Left, false)
	released := frame(t, &ctx, state)
	testing.expect(t, !released.clicked && ctx.active == 0 && ctx.capture.mouse)
	input.clear(&state)
	frame(t, &ctx, state)
	testing.expect(t, !ctx.capture.mouse)
	input.record_cursor(&state, {60, 60})
	input.record_mouse_button(&state, .Left, true)
	frame(t, &ctx, state)
	input.clear(&state)
	input.record_mouse_button(&state, .Left, false)
	testing.expect(t, frame(t, &ctx, state).clicked)
	input.clear(&state)
	testing.expect(t, !frame(t, &ctx, state).clicked)
	input.record_mouse_button(&state, .Left, true)
	input.record_mouse_button(&state, .Left, false)
	testing.expect(t, frame(t, &ctx, state).clicked)
}

@(test)
test_world_drag_and_disappearing_control :: proc(t: ^testing.T) {
	ctx := create()
	defer destroy(&ctx)
	state: input.State
	input.init(&state, true, {300, 160})
	input.record_mouse_button(&state, .Left, true)
	frame(t, &ctx, state)
	input.clear(&state)
	input.record_cursor(&state, {60, 60})
	result := frame(t, &ctx, state)
	game := remaining_input(&ctx)
	testing.expect(t, !result.held && !result.clicked && !ctx.capture.mouse)
	testing.expect(t, input.mouse_down(&game, .Left) && game.mouse_delta.x != 0)
	input.clear(&state)
	input.record_mouse_button(&state, .Left, false)
	testing.expect(t, !frame(t, &ctx, state).clicked)
	input.clear(&state)
	input.record_mouse_button(&state, .Left, true)
	frame(t, &ctx, state)
	input.clear(&state)
	input.record_cursor(&state, {300, 160})
	testing.expect(t, begin(&ctx, state, {200, 100}, {400, 200}) == .None)
	testing.expect(t, end(&ctx) == .None)
	testing.expect(t, ctx.active == 0 && ctx.focus == 0 && ctx.capture.mouse)
	input.clear(&state)
	input.record_mouse_button(&state, .Left, false)
	frame(t, &ctx, state)
	testing.expect(t, ctx.capture.mouse)
	input.record_focus(&state, false)
	frame(t, &ctx, state)
	testing.expect(
		t,
		ctx.active == 0 && ctx.focus == 0 && !ctx.capture.mouse && !ctx.capture.keyboard,
	)
}

@(test)
test_keyboard_focus_and_key_ownership :: proc(t: ^testing.T) {
	ctx := create()
	defer destroy(&ctx)
	state: input.State
	input.init(&state, true, {300, 160})
	frame(t, &ctx, state, true)
	input.record_key(&state, .Tab, true)
	frame(t, &ctx, state, true)
	testing.expect_value(t, ctx.focus, id("first"))
	input.clear(&state)
	input.record_key(&state, .Tab, false)
	frame(t, &ctx, state, true)
	input.clear(&state)
	input.record_key(&state, .Tab, true)
	frame(t, &ctx, state, true)
	testing.expect_value(t, ctx.focus, id("second"))
	input.clear(&state)
	input.record_key(&state, .Tab, false)
	frame(t, &ctx, state, true)
	input.clear(&state)
	input.record_key(&state, .Left_Shift, true)
	input.record_key(&state, .Tab, true)
	frame(t, &ctx, state, true)
	testing.expect_value(t, ctx.focus, id("first"))
	input.clear(&state)
	input.record_key(&state, .Tab, false)
	input.record_key(&state, .Left_Shift, false)
	input.record_key(&state, .Space, true)
	testing.expect(t, frame(t, &ctx, state, true).clicked)
	input.clear(&state)
	testing.expect(t, !frame(t, &ctx, state, true).clicked)
	input.record_mouse_button(&state, .Left, true)
	frame(t, &ctx, state, true)
	game := remaining_input(&ctx)
	testing.expect(t, ctx.focus == 0 && !input.down(&game, .Space))
	input.clear(&state)
	input.record_key(&state, .Space, false)
	frame(t, &ctx, state, true)
	game = remaining_input(&ctx)
	testing.expect(t, !input.released(&game, .Space))
	input.clear(&state)
	input.record_key(&state, .Space, true)
	frame(t, &ctx, state, true)
	game = remaining_input(&ctx)
	testing.expect(t, input.pressed(&game, .Space))
}

@(test)
test_layout_clipping_and_ids :: proc(t: ^testing.T) {
	column, err := layout({{10, 20}, {120, 100}}, .Column, padding = 10, spacing = 4)
	testing.expect(t, err == .None)
	first, first_error := next(&column, 20)
	testing.expect(t, first_error == .None)
	testing.expect_value(t, first, (Rect{{20, 30}, {100, 20}}))
	second, second_error := next(&column, 30)
	testing.expect(t, second_error == .None)
	testing.expect_value(t, second.position, ([2]f32{20, 54}))
	row, _ := layout(second, .Row, spacing = 8)
	left, _ := next(&row, 20)
	right, _ := next(&row, 72)
	testing.expect_value(t, left, (Rect{{20, 54}, {20, 30}}))
	testing.expect_value(t, right, (Rect{{48, 54}, {72, 30}}))
	_, overflow := next(&column, 40)
	testing.expect(t, overflow == .Layout_Overflow)
	ctx := create()
	defer destroy(&ctx)
	state: input.State
	input.init(&state, true, {50, 50})
	input.record_mouse_button(&state, .Left, true)
	testing.expect(t, begin(&ctx, state, {100, 100}, {100, 100}) == .None)
	testing.expect(t, draw2d.push_clip(&ctx.draws, {{0, 0}, {20, 20}}) == .None)
	result, interaction_error := interact(&ctx, id("clipped"), {{0, 0}, {80, 80}})
	testing.expect(t, interaction_error == .None && !result.held && !result.hovered)
	_, duplicate := interact(&ctx, id("clipped"), {{0, 0}, {80, 80}})
	testing.expect(t, duplicate == .Duplicate_ID)
	testing.expect(t, draw2d.pop_clip(&ctx.draws) == .None)
	testing.expect(t, end(&ctx) == .None)
	testing.expect(t, !ctx.capture.mouse)
	testing.expect(t, id("toggle", id("one")) != id("toggle", id("two")))
}
